### ISSUE TITLE
Documentation and examples of winnus

### ISSUE THREAD

**Issue by OwenBrotherwood** [espruino/winnus#3]
https://github.com/OwenBrotherwood/winnus/tree/docExample 
- are available for pull at espruino discretion.

---

This is my suggestion as to how to indicate a work in progress where the work is done on my own branch and a clear indication in the issue that the branch is ready if acceptable rather than a pull request and ensuing spam.
No comment needed if ok.

**Comment by gfwilliams** [comment]
Looks great - thanks! Just pulled.

In future, if instead of the 'Ok to pull' commit, you just issue a pull request from a branch when ready, I can merge it easily.

It's just when you issue a pull request and continue to commit to it, I have no idea if I should be merging it or not.
